//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatingChart
    {
        public int seat_id { get; set; }
        public int section { get; set; }
        public int seat { get; set; }
        public int isTaken { get; set; }
        public int flight_id { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
